baseURL = "https://mysteryven.com"
languageCode = "en-us"
title = "Mysteryven's Blog"
theme = "sam"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-171080709-1"

[outputs]
home = ["HTML", "RSS", "Bonsai"]

[outputFormats.Bonsai]
baseName = "bonsai"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.bonsai]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "技术"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "生活"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    name = "分类"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
    since = 2020
    author = "mysteryven"                           # Author's name
    avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "Push My Boundaries."         # Subtitle
    cdn_url = ""           # Base CDN URL
    # home_mode = "post" # post or other

    google_verification = ""

    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "mysteryven"
    Email   = "mysteryven#gmail.com"

[[params.mainMenu]]
    link = "/"
    text = "首页"

[[params.mainMenu]]
    link = "/articles"
    text = "喜欢的文章"

[[params.mainMenu]]
    link = "/posts/"
    text = "想写的文章"

[[params.mainMenu]]
    link = "/about"
    text = "我是谁?"